#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "~/.Xmodmap"

# Applications you want to run with fluxbox.
nm-applet &
conky &
~/bin/soundstartup &

# And last but not least we start fluxbox.
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/root/.fluxbox/log"
# fbsetbg -f ~/.fluxbox/backgrounds/debian_code_over_commercial.jpg
